apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker operator will be installed.
namespace: spinnaker-operator

resources:
  - operator-ns.yml
  - spinnaker.armory.io_spinnakerservices_crd.yaml
  - spinnaker.io_spinnakeraccounts_crd.yaml
  - deployment.yaml
  - halyard_config_map.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml

#patchesStrategicMerge:
#  - patch-operator_version.yaml

images:
- name: the-my-app
- newName: my.docker.registry.com/my-project/my-app
  newTag: test
