apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where spinnaker operator will be installed.
namespace: spinnaker-operator

resources:
  - operator-ns.yml
  - spinnaker.armory.io_spinnakerservices_crd.yaml
  - spinnaker.io_spinnakeraccounts_crd.yaml
  - deployment.yaml
  - halyard_config_map.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml

images:
- name: spinnaker-operator
  newName: armory/armory-operator
  newTag: 1.2.5
- name: halyard
  newName: armory/halyard-armory
  newTag: 1.10.1-2669348-operator
