apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-operator
spec:
  template:
    spec:
      containers:
        - name: spinnaker-operator
          image: armory/armory-operator:1.2.7
        - name: halyard
          image: armory/halyard-armory:1.12.0-347c870-operator
